apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "500"
data:
  config.toml: |-
    concurrent = 4
    [[runners]]
      name = "Kubernetes Demo Runner"
      url = "https://gitlab.{{ .Values.domain }}/ci"
      token = "{{ .Values.runnerToken }}"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab"
        image = "ubuntu:24.04"
        poll_timeout = 600
        cpu_request = "1"
        service_cpu_request = "200m" 
      [runners.cache]
        Type = "s3"
        Path = ""
        Shared = false
        [runners.cache.s3]
          ServerAddress = "{{ .Values.minio.serverAddress }}"
          AccessKey = "{{ .Values.minio.accessKey_b64 | b64dec }}"
          SecretKey = "{{ .Values.minio.secretKey_b64 | b64dec }}"
          BucketName = "runner-cache"
          Insecure = false
          ServerSideEncryption = "S3"
