apiVersion: v1
data:
  password: {{ .Values.postgresql.base64Password }}
kind: Secret
metadata:
  creationTimestamp: null
  name: gitlab-postgresql-password
  annotations:
    argocd.argoproj.io/sync-wave: "300"
