apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    app: prometheus
    chart: prometheus-15.18.0
    component: server
    heritage: Helm
    release: gitlab
  name: gitlab-prometheus-server
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gp2
  volumeMode: Filesystem