apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    app: minio
    app.kubernetes.io/component: minio
    app.kubernetes.io/instance: gitlab-minio
    app.kubernetes.io/managed-by: gitlab-operator
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/part-of: gitlab
    chart: minio-0.4.3
    heritage: Helm
    release: gitlab
  name: gitlab-minio
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.minio.size }}
  storageClassName: {{ .Values.pvc.minio.storageClass }}
  volumeMode: Filesystem