apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/name: redis
  name: redis-data-gitlab-redis-master-0
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.redis.size }}
  storageClassName: {{ .Values.pvc.redis.storageClass }}
  volumeMode: Filesystem
